# this is a (failed) attempt at starting three containers with static IP
# addresses in an internal network
#
version: "3"
services:
  stp:
    image: osmo-stp-master
    deploy:
      mode: global
      restart_policy:
        condition: none
    networks:
      sigtran:
        ipv4_address: 172.18.0.200

  m3ua:
    image: m3ua-test
    deploy:
      mode: global
      restart_policy:
        condition: none
    depends_on:
      - stp
    networks:
      sigtran:
        ipv4_address: 172.18.0.2

  sua:
    image: sua-test
    deploy:
      mode: global
      restart_policy:
        condition: none
    depends_on:
      - stp
    networks:
      sigtran:
        ipv4_address: 172.18.0.3

networks:
  sigtran:
    # this apparently was working in the past, but only overlay is
    # supported now?
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
